apiVersion: v1
kind: Namespace
metadata:
  name: ${space}
  labels:
    toolkit.fluxcd.io/tenant: dev-team
    test: ${quote}${id}${quote}
    testing: ${space}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: ${id}
    targetPort: http-web-svc
